/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrochureRouteImport } from './routes/brochure'
import { Route as CallForPapersRouteImport } from './routes/call-for-papers'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiRegisterRouteImport } from './routes/api/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrochureRoute = BrochureRouteImport.update({
  id: '/brochure',
  path: '/brochure',
  getParentRoute: () => rootRouteImport,
} as any)
const CallForPapersRoute = CallForPapersRouteImport.update({
  id: '/call-for-papers',
  path: '/call-for-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brochure': typeof BrochureRoute
  '/call-for-papers': typeof CallForPapersRoute
  '/committees': typeof CommitteesRoute
  '/guidelines': typeof GuidelinesRoute
  '/register': typeof RegisterRoute
  '/api/contact': typeof ApiContactRoute
  '/api/register': typeof ApiRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brochure': typeof BrochureRoute
  '/call-for-papers': typeof CallForPapersRoute
  '/committees': typeof CommitteesRoute
  '/guidelines': typeof GuidelinesRoute
  '/register': typeof RegisterRoute
  '/api/contact': typeof ApiContactRoute
  '/api/register': typeof ApiRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brochure': typeof BrochureRoute
  '/call-for-papers': typeof CallForPapersRoute
  '/committees': typeof CommitteesRoute
  '/guidelines': typeof GuidelinesRoute
  '/register': typeof RegisterRoute
  '/api/contact': typeof ApiContactRoute
  '/api/register': typeof ApiRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brochure'
    | '/call-for-papers'
    | '/committees'
    | '/guidelines'
    | '/register'
    | '/api/contact'
    | '/api/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brochure'
    | '/call-for-papers'
    | '/committees'
    | '/guidelines'
    | '/register'
    | '/api/contact'
    | '/api/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brochure'
    | '/call-for-papers'
    | '/committees'
    | '/guidelines'
    | '/register'
    | '/api/contact'
    | '/api/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrochureRoute: typeof BrochureRoute
  CallForPapersRoute: typeof CallForPapersRoute
  CommitteesRoute: typeof CommitteesRoute
  GuidelinesRoute: typeof GuidelinesRoute
  RegisterRoute: typeof RegisterRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brochure': {
      id: '/brochure'
      path: '/brochure'
      fullPath: '/brochure'
      preLoaderRoute: typeof BrochureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-for-papers': {
      id: '/call-for-papers'
      path: '/call-for-papers'
      fullPath: '/call-for-papers'
      preLoaderRoute: typeof CallForPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrochureRoute: BrochureRoute,
  CallForPapersRoute: CallForPapersRoute,
  CommitteesRoute: CommitteesRoute,
  GuidelinesRoute: GuidelinesRoute,
  RegisterRoute: RegisterRoute,
  ApiContactRoute: ApiContactRoute,
  ApiRegisterRoute: ApiRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
